### ISSUE TITLE
consolidate calculate_metrics

### ISSUE THREAD

**Issue by georgeslabreche** [georgeslabreche/opssat-onboard-image-denoiser#74]
It should always be executed from here:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/main/results/calculate_metrics.py

Implement this FIXME:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/b68c918e797137d8342bd2956243b12c8fe68245/results/calculate_metrics.py#L137-L141

And this one as well:
https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/b68c918e797137d8342bd2956243b12c8fe68245/results/calculate_metrics.py#L173-L177

Delete all other calculate_metrics, that is:

- [x] ./flatsat/calculate_metrics.py

- [x] ./spacecraft/calculate_metrics.py

**Comment by cguz** [comment]
Jo Jo @georgeslabreche 

I did a first version. Now, it is executed from:

https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/74-consolidate-calculate_metrics/results/calculate_metrics.py

However, to unify the two functions is not straightforward:


https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/0aa41a7f1705ce0af3cbfd6545ae1618efd0a0b9/results/calculate_metrics.py#L40-L45

https://github.com/georgeslabreche/opssat-onboard-image-denoiser/blob/0aa41a7f1705ce0af3cbfd6545ae1618efd0a0b9/results/calculate_metrics.py#L78-L85

First, it requires to:

- [ ]  unify the structure/files of the flatsat and spacecraft folders. 

Please, take a look
